version: "3.9"

services:

  # MongoDB
  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: bc19cyl
      MONGO_INITDB_ROOT_PASSWORD: bc19cyl
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' |  mongo mongodb://bc19cyl:bc19cyl@mongodb:27017 --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Bot COVID19 interactivo CYL
  botcovidinteractivo:
    image: rafa93m/bot_covid19cyl_interactivo
    container_name: "bot_covid19cyl_interactivo"
    environment:
      - TELEGRAM_TOKEN=123456:123456789123456789123
      - URI_MONGODB=mongodb://bc19cyl:bc19cyl@mongodb:27017/bc19cyl?authSource=admin
      - ID_ADMIN=123456
      - LOGLEVEL=DEBUG
    depends_on:
      - mongodb
    restart: unless-stopped
